#!/usr/bin/env python3
"""Prepare page-reviewed annual-report milestones and dated quoted price ranges."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SCRATCH=ROOT/'.local-data/rak-annual-pass36';BASE=ROOT/'data/historical-intelligence'
FLAMINGO='project:rak-properties-flamingo-villas-in-mina-for-sale-ras-al-khaimah-uae';MINA='community:Ras Al Khaimah:mina-al-arab'
PINS={
 'annual-2015':('9dcadc214cc3850ab82f3b6f9b1e9c6584cbf14b5dbe3ede948fe57e66c8e064',[18,20]),
 'annual-2016':('6c0dd924f35e33a61bb3d9ab0907c8cebaa066dab20df4a2950e2cffe833189e',[27,29]),
 'annual-2017':('c33dfcd1898670d5446f7718552a40e6e88bfbb4e9990beb94e31f31cb769fa6',[17]),
 'annual-2018':('c2ef31905450fd3d4ac60451430a41f6e926d8cd8d6486b7d6d74ab893953dd9',[23]),
 'annual-2019':('c6727c0e3189b551cd70ab5621b7fb2b32aa8070b5cd370f1c75f01017b1a2ac',[21,24]),
 'flamingo-launch-2013':('7a31174c5948a1c6c9aa6f95e16d998bd542c0dd23fabd77942c0e396742f445',[])}

def main():
 s=json.loads((ROOT/'data/historical-intelligence-20261003.json').read_bytes());assert s['version']=='20261008-enrichment-v35'
 records={r['id']:r for r in s['records']};sources=[];source_by_key={};facts=[]
 for key,(pin,pages) in PINS.items():
  c=json.loads((SCRATCH/(key+'-capture.json')).read_text());ext='pdf' if pages else 'html'
  assert c['sha256']==pin==hashlib.sha256((SCRATCH/(key+'.'+ext)).read_bytes()).hexdigest()
  assert not any(x.get('url')==c['url'] for x in s['sources'])
  x={**c,'id':'rak36-'+key,'title':('RAK Properties Annual Report '+key[-4:] if pages else 'The National: Emirati and Indian buyers snap up RAK waterfront properties'),'publisher':'RAK Properties' if pages else 'The National','primaryEvidence':bool(pages),'classification':'primary_developer_annual_report' if pages else 'contemporaneous_reporting_developer_interview','publishedAt':None if pages else '2013-10-09','firstAvailableAt':c['retrievedAt'],'publicationDateStatus':'Unknown; report year, signature and upload path do not prove publication date' if pages else 'Article displays 9 October 2013; present page metadata records a later modification on 17 June 2021','availabilityBasis':'This exact captured vintage first verified at retrieval; no earlier model availability inferred','reviewedPages':pages,'visualPagesChecked':bool(pages),'licence':'rights_pending: minimal attributed facts only; raw articles, PDFs and rendered pages are not redistributed','rawBodyRedistributed':False}
  if pages:x['reportingPeriod']=key[-4:]
  else:x['pageModifiedAt']='2021-06-17T12:44:08.759Z'
  sources.append(x);source_by_key[key]=x
 basis={FLAMINGO:'Exact Flamingo Villas Mina record matches RAK Properties, Flamingo and Mina Al Arab in Ras Al Khaimah. Phase I, Phase II and the 2013 launch cohort stay explicitly scoped within this umbrella record; Dubai Flamingo Residence is excluded.',MINA:'Exact Mina Al Arab community in Ras Al Khaimah is explicitly named by the source. Named components remain community phase evidence; no automatic alias or project fan-out.'}
 def common(rid,code,key,proof=()):
  x=source_by_key[key];ids=[x['id']]+[source_by_key[p]['id'] for p in proof]
  return {'id':'rak36-'+code,'recordId':rid,'status':'accepted','sourceIds':ids,'identitySourceIds':ids,'identityVerified':True,'identityBasis':basis[rid],'primaryEvidence':x['primaryEvidence'],'publishedAt':x['publishedAt'],'firstAvailableAt':max(z['firstAvailableAt'] for z in sources if z['id'] in ids)}
 def life(rid,code,key,kind,start,precision,label,page=None,phase=None,planned=False,end=None,related=(),reconciliation=None,proof=()):
  date={'start':start,'precision':precision}
  if end:date['end']=end
  f={**common(rid,code,key,proof),'kind':'lifecycle','milestone':kind,'date':date,'scope':'subject_phase' if phase else 'published_reference','verification':'reported','eventStatus':'planned' if planned else 'reported','evidenceClass':'primary_developer_reported_milestone' if source_by_key[key]['primaryEvidence'] else 'contemporaneously_reported_milestone','label':label,'note':'Named phase/component evidence only. No whole-community completion, legal certificate, actual occupancy, financial price or automatic uplift is established.' if phase else 'Reported historical announcement year; not a proven first-ever inception boundary or proof that earlier land prices did not exist.','dateBasis':('Annual report '+key[-4:]+', PDF page '+str(page)) if page else 'Dated article; native month/year precision retained','preserveAdditionalLifecycleFields':True}
  if page:f['sourcePage']=page
  if phase:f['phaseLabel']=phase
  if related:f['relatedMilestoneIds']=list(related)
  if reconciliation:f['dateReconciliation']=reconciliation;f['note']+=' '+reconciliation
  facts.append(f)
 # Exact umbrella project; neither phase is relabelled whole-project completion.
 life(FLAMINGO,'flamingo-launch-cohort','flamingo-launch-2013','phase_announcement','2013-10','month','Report describes launch of a 104-villa Flamingo cohort in October 2013.',phase='2013 launch cohort; reported inventory 104 villas')
 life(FLAMINGO,'flamingo-phase2-announcement','annual-2015','phase_announcement','2015-05','month','Developer reports announcing Flamingo Phase II in May 2015.',18,'Flamingo Phase II')
 reconciliation='The later Q2 2024 timeline reports community delivery in 2017. Earlier named phase handovers are retained separately; the difference in scope and date is unresolved and neither report replaces the other.'
 life(FLAMINGO,'flamingo-phase1-handover','annual-2015','phase_handover','2015','year','Developer reports Flamingo Phase I handed over in 2015.',20,'Flamingo Phase I',related=['rak35-flamingo-delivery'],reconciliation=reconciliation,proof=['annual-2016'])
 life(FLAMINGO,'flamingo-phase2-development','annual-2015','phase_development_start','2015','year','Developer reports starting development of Flamingo Phase II in 2015.',20,'Flamingo Phase II',reconciliation='Development commencement is not converted into a verified physical construction-start date.')
 life(FLAMINGO,'flamingo-phase2-target','annual-2015','target_handover','2016-Q4','quarter','The 2015 report targeted Flamingo Phase II handover in Q4 2016.',20,'Flamingo Phase II',planned=True)
 life(FLAMINGO,'flamingo-phase2-handover','annual-2016','phase_handover','2016-10','month','Developer reports Flamingo Phase II handover in October 2016.',27,'Flamingo Phase II',related=['rak35-flamingo-delivery','rak36-flamingo-phase2-target'],reconciliation=reconciliation)
 # Master development: named components only; no assignment to ambiguous catalogue projects.
 life(MINA,'mina-reported-launch','flamingo-launch-2013','announcement','2005','year','Contemporaneous reporting retrospectively places Mina Al Arab launch in 2005.')
 life(MINA,'mina-flamingo-phase1-handover','annual-2015','phase_handover','2015','year','Flamingo Phase I within Mina is reported handed over in 2015.',20,'Flamingo Phase I',related=['rak35-mina-flamingo-delivery'],reconciliation=reconciliation,proof=['annual-2016'])
 life(MINA,'mina-flamingo-phase2-handover','annual-2016','phase_handover','2016-10','month','Flamingo Phase II within Mina is reported handed over in October 2016.',27,'Flamingo Phase II',related=['rak35-mina-flamingo-delivery'],reconciliation=reconciliation)
 life(MINA,'mina-bermuda-progress','annual-2015','phase_construction_progress','2015','year','Bermuda Villas construction within Mina is reported in progress in 2015.',20,'Bermuda Villas')
 life(MINA,'mina-bermuda-target-2016','annual-2015','target_handover','2016-Q4','quarter','The 2015 report targeted Bermuda Villas handover in Q4 2016.',20,'Bermuda Villas',planned=True)
 life(MINA,'mina-bermuda-target-2017','annual-2016','target_handover','2017-01-01','range','The 2016 report targeted Bermuda Villas handover in H1 2017.',29,'Bermuda Villas',planned=True,end='2017-06-30',related=['rak36-mina-bermuda-target-2016'],reconciliation='Revised schedule retained alongside the earlier Q4 2016 target; interval endpoints express H1, not exact handover days.')
 life(MINA,'mina-bermuda-handover','annual-2017','phase_handover','2017','year','The 2017 report records Bermuda Villas handover within Mina.',17,'Bermuda Villas',related=['rak36-mina-bermuda-target-2017','rak35-mina-bermuda-delivery'],reconciliation='Earlier annual report and later timeline are the same publisher, not independent corroboration; no exact handover day or occupancy inferred.')
 for code,label in [('gateway','Gateway Residence'),('north-bay','North Bay Residence')]:
  life(MINA,'mina-'+code+'-launch','annual-2017','phase_announcement','2017','year',label+' within Mina is reported launched during 2017.',17,label+' as named in the 2017 report',reconciliation='No mapping to an ambiguous Gateway/South Bay catalogue phase. The source-native 2017 launch claim is retained separately from later campaigns.')
 life(MINA,'mina-gateway-progress-2018','annual-2018','phase_construction_progress','2018','year','Gateway Residence is reported under construction in the 2018 report.',23,'Gateway Residence as named in the 2018 report')
 life(MINA,'mina-gateway-target-2019','annual-2018','target_handover','2019','year','The 2018 report targeted Gateway Residence handover during 2019.',23,'Gateway Residence as named in the 2018 report',planned=True)
 life(MINA,'mina-gateway-nearing-handover','annual-2019','phase_construction_progress','2019','year','The 2019 report describes Gateway Residence as nearing handover.',24,'Gateway Residence as named in the 2019 report',related=['rak36-mina-gateway-target-2019','rak35-mina-gateway-delivery'],reconciliation='Nearing handover is a qualitative report, not 100% progress or confirmed delivery; the later timeline retains a 2020 delivery year.')
 for code,label in [('marbella','Marbella Villas'),('bay','Bay Residence')]:
  life(MINA,'mina-'+code+'-construction-target','annual-2018','target_construction_start','2019','year','The 2018 report targeted '+label+' construction commencement in 2019.',23,label+' as named in the 2018 report',planned=True,reconciliation='Original named component only; no transfer to Marbella Phase II or an unverified Bay phase.')
 life(MINA,'mina-marbella-progress','annual-2019','phase_construction_progress','2019','year','Marbella villa-community construction is reported progressing in 2019.',24,'Marbella villa community as named in the 2019 report',related=['rak36-mina-marbella-construction-target'])
 for code,label,word in [('anantara','Anantara Mina Al Arab hotel','late'),('intercontinental','InterContinental Mina Al Arab hotel','by the end of')]:
  life(MINA,'mina-'+code+'-progress','annual-2017','phase_construction_progress','2017','year',label+' is reported under construction in the 2017 report.',17,label,reconciliation='Hotel component, not the later branded-residences catalogue project.')
  life(MINA,'mina-'+code+'-opening-target','annual-2017','target_opening','2019','year','The 2017 report targeted '+label+' opening '+word+' 2019.',17,label,planned=True)
  life(MINA,'mina-'+code+'-completion-target','annual-2019','target_completion','2021','year','The 2019 report targeted '+label+' completion in early 2021.',21,label,planned=True,related=['rak36-mina-'+code+'-opening-target'],reconciliation='Earlier opening target and later completion target remain distinct milestone types. Early 2021 is not converted to an exact quarter/day; actual opening is not established here.')
 # One range is one observation. Endpoints are neither two sales nor a median.
 for rid,code,low,high,segment in [(FLAMINGO,'flamingo-advertised-range',750000,2500000,'Flamingo 2013 launch cohort of 104 villas; mixed sizes, individual unit identities unknown'),(MINA,'mina-apartment-advertised-range',295000,1200000,'Remaining apartments from the previously developed 808-apartment cohort; remaining count, buildings and individual unit identities unknown')]:
  facts.append({**common(rid,code,'flamingo-launch-2013',proof=['annual-2015']),'kind':'financial','scope':'published_reference','evidenceClass':'historical_reported_advertised_price_range','observation':{'metric':'price','value':low,'unit':'AED','period':'2013-10-09','frequency':'daily','segment':segment,'observationKind':'asking_quote','currentSnapshotEligible':False,'includeInCurrentSnapshot':False,'quoteQualifier':'Reported asking range across the stated cohort; not a transaction, average, valuation or current offer','sourceQuoteBasis':'Contemporaneous developer interview reported by The National on 9 October 2013','observationDateBasis':'Article reporting date for the offered range; individual quotation and transaction dates are not established','quotedPriceRange':{'low':low,'high':high,'unit':'AED','basis':'Range across the source-native cohort; no average or midpoint derived'},'note':'The stored value is the lower endpoint solely for schema compatibility; the range and cohort must be shown together. No financial return is calculated from either endpoint.'}})
 checks=[{'recordId':rid,'catalogueName':records[rid]['name'],'type':records[rid]['type'],'emirate':records[rid]['emirate'],'identityVerified':True,'basis':basis[rid]} for rid in [FLAMINGO,MINA]]
 for rid in [FLAMINGO,MINA]:
  ids={f['id'] for f in facts if f['recordId']==rid}|{f['id'] for f in records[rid]['lifecycle']}
  assert all(set(f.get('relatedMilestoneIds',[]))<=ids for f in facts if f['recordId']==rid)
 collection={'projectRecords':1,'communityRecords':1,'acceptedLifecycleFacts':sum(f['kind']=='lifecycle' for f in facts),'acceptedAdvertisedRanges':2,'newSources':len(sources),'registeredSaleOrRentObservationsAdded':0,'currentValuationsAdded':0,'approved2080Forecasts':0,'rawBodiesRedistributed':False}
 packet={'version':1,'passId':'rak-annual-pass36-20261008','asOf':s['asOf'],'priorVersion':s['version'],'candidateVersion':'20261008-enrichment-v36','sources':sources,'facts':facts,'seriesLinks':[],'recordIdentityChecks':checks,'collection':collection,'conflicts':[{'field':'flamingo_phase_and_community_delivery','resolution':reconciliation},{'field':'project_schedules','resolution':'Earlier targets, later targets and reported delivery are separately dated; none silently replaces prior schedules.'}],'excludedCandidates':[{'source':'annual-2014','reason':'Vague prior-years handover discussion does not establish an exact new dated milestone. Capture is retained privately; no source or coverage credit added.'},{'field':'corporate_financials_and_occupancy','reason':'Company revenue/assets/budgets and qualitative community occupancy do not establish subject prices, valuations, occupancy percentages or rental-start dates.'},{'field':'2018_unnamed_205_home_project','reason':'No exact phase mapping inferred for the unnamed 205-home launch or its H1 construction target.'},{'field':'undated_earlier_villa_price_range','reason':'The 2013 article gives earlier villa prices without an observation date; no year-specific price point is invented.'},{'field':'generic_gateway_south_bay_granada_and_anantara_residences','reason':'Component-level evidence is retained only on the exact Mina community. No numeric phase fan-out or hotel-to-residences mapping.'}],'methodology':'Exact parent identities, explicitly named component/phase scope, visual report-page review and checksummed captures. News quotes remain published references with native price ranges. Endpoints are not separate transactions or averages. Source publication, observation and capture-time availability are distinct. All prior data and superseded schedules remain retained.'}
 (BASE/'rak-properties-annual-pass36-20261008.json').write_text(json.dumps(packet,ensure_ascii=False,indent=2)+'\n');print(json.dumps(collection))
if __name__=='__main__':main()
