#!/usr/bin/env python3
"""Compile reviewed FY2024 native sales vintages and exact component milestones."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'data/historical-intelligence';SCRATCH=ROOT/'.local-data/rak-financial-pass37'
MINA='community:Ras Al Khaimah:mina-al-arab';NB='project:nb-collection-by-rak-properties-on-hayat-island'
def main():
 s=json.loads((ROOT/'data/historical-intelligence-20261003.json').read_bytes());assert s['version']=='20261008-enrichment-v36'
 records={r['id']:r for r in s['records']};prior={x['id']:x for x in s['sources']};captures={key:json.loads((SCRATCH/(key+'-capture.json')).read_text()) for key in ['rak-fy2024','ihg-opening-2022']}
 captures['nb-launch']=json.loads((SCRATCH/'nb-launch-capture.json').read_text())
 sources=[]
 for key,pin,title,publisher,publication,filename,pages in [
  ('rak-fy2024','fee42a8a605875cd76986502b7a888bcb3c52b319afcb659a1210f7d9fd0fb59','RAK Properties FY2024 investor report, pages 10 and 30','RAK Properties',None,SCRATCH/'rak-fy2024.pdf',[10,30]),
  ('nb-launch','744dc5ad1f2a274e1c71f7e66affcfa253062530cdde120d81568b86ac6ce57e','NB Collection launch on Hayat Island, 26 June 2024','RAK Properties','2024-06-26',SCRATCH/'nb-launch.html',[]),
  ('ihg-opening-2022','94fd6b655ddf2728e627455a578ca8f46baad27e4fac113cdcd118f0e52dd77b','InterContinental Ras Al Khaimah Mina Al Arab opening announcement','IHG Hotels & Resorts','2022-03-03',SCRATCH/'ihg-opening-2022.html',[])]:
  c=captures[key];assert c['sha256']==pin==hashlib.sha256(filename.read_bytes()).hexdigest();assert c['httpStatus']==200
  assert not any(x.get('url')==c['url'] for x in s['sources'])
  source={**{k:v for k,v in c.items() if k!='status'},'id':'rak37-'+key,'title':title,'publisher':publisher,'publishedAt':publication,'firstAvailableAt':c['retrievedAt'],'primaryEvidence':True,'classification':'primary_developer_investor_report' if pages else 'primary_operator_announcement','publicationDateStatus':'Unknown; reporting period and upload path do not establish publication day' if pages else 'Date displayed by the issuing organisation; this captured vintage was first verified at retrieval','availabilityBasis':'Current source vintage first verified at retrieval; no historical backtest availability inferred','reviewedPages':pages,'visualPagesChecked':bool(pages),'licence':'rights_pending: minimal attributed facts only; raw PDFs, articles and rendered pages are not redistributed','rawBodyRedistributed':False}
  if pages:source.update(reportingPeriod='2024',pageCount=51)
  sources.append(source)
 source_by_id={**prior,**{x['id']:x for x in sources}};financial_source=sources[0];facts=[];checks=[];native=[]
 def common(rid,code,sourceid,basis,proof):
  x=source_by_id[sourceid]
  return {'id':'rak37-'+code,'recordId':rid,'status':'accepted','sourceIds':[sourceid],'identitySourceIds':proof,'identityVerified':True,'identityBasis':basis,'primaryEvidence':True,'publishedAt':x['publishedAt'],'firstAvailableAt':max(source_by_id[p]['firstAvailableAt'] for p in set(proof+[sourceid]))}
 def life(rid,code,sourceid,basis,proof,kind,date,label,note,scope='subject',verification='reported',**extra):
  facts.append({**common(rid,code,sourceid,basis,proof),'kind':'lifecycle','milestone':kind,'date':date,'scope':scope,'verification':verification,'eventStatus':'reported','evidenceClass':'primary_operator_reported_milestone','label':label,'note':note,'preserveAdditionalLifecycleFields':True,**extra})
 oldpacket=json.loads((BASE/'rak-properties-investor-pass35-20261008.json').read_text());by_label={x['sourceProjectLabel']:x for x in oldpacket['nativeSalesSnapshots']};oldchecks={x['recordId']:x for x in oldpacket['recordIdentityChecks']}
 reviewed={'sourceSHA256': 'fee42a8a605875cd76986502b7a888bcb3c52b319afcb659a1210f7d9fd0fb59', 'reviewedPage': 30, 'asOf': '2024-12-31', 'rows': [{'sourceProjectLabel': 'Gateway 2', 'unitsLaunched': 146, 'unitsSold': 146, 'netSalesAEDMillion': 164, 'revenueBacklogAEDMillion': 1, 'reportedSoldPercent': 100, 'reportedCompletePercent': 99}, {'sourceProjectLabel': 'Bayviews', 'unitsLaunched': 344, 'unitsSold': 344, 'netSalesAEDMillion': 421, 'revenueBacklogAEDMillion': 240, 'reportedSoldPercent': 100, 'reportedCompletePercent': 43}, {'sourceProjectLabel': 'Bay Residence Phase 1', 'unitsLaunched': 324, 'unitsSold': 324, 'netSalesAEDMillion': 364, 'revenueBacklogAEDMillion': 18, 'reportedSoldPercent': 100, 'reportedCompletePercent': 95}, {'sourceProjectLabel': 'Bay Residence Phase 2', 'unitsLaunched': 324, 'unitsSold': 324, 'netSalesAEDMillion': 395, 'revenueBacklogAEDMillion': 62, 'reportedSoldPercent': 100, 'reportedCompletePercent': 84}, {'sourceProjectLabel': 'Marbella Extension', 'unitsLaunched': 89, 'unitsSold': 85, 'netSalesAEDMillion': 225, 'revenueBacklogAEDMillion': 0, 'reportedSoldPercent': 95, 'reportedCompletePercent': 99}, {'sourceProjectLabel': 'Cape Hayat', 'unitsLaunched': 678, 'unitsSold': 650, 'netSalesAEDMillion': 965, 'revenueBacklogAEDMillion': 617, 'reportedSoldPercent': 96, 'reportedCompletePercent': 36}, {'sourceProjectLabel': 'Granada Extension', 'unitsLaunched': 80, 'unitsSold': 69, 'netSalesAEDMillion': 184, 'revenueBacklogAEDMillion': 82, 'reportedSoldPercent': 86, 'reportedCompletePercent': 55}, {'sourceProjectLabel': 'Quattro Del Mar', 'unitsLaunched': 888, 'unitsSold': 507, 'netSalesAEDMillion': 687, 'revenueBacklogAEDMillion': 606, 'reportedSoldPercent': 57, 'reportedCompletePercent': 12}, {'sourceProjectLabel': 'The Edge', 'unitsLaunched': 237, 'unitsSold': 188, 'netSalesAEDMillion': 205, 'revenueBacklogAEDMillion': 205, 'reportedSoldPercent': 80, 'reportedCompletePercent': 'NIL'}, {'sourceProjectLabel': 'NB Collections', 'unitsLaunched': 11, 'unitsSold': 1, 'netSalesAEDMillion': 24, 'revenueBacklogAEDMillion': 24, 'reportedSoldPercent': 9, 'reportedCompletePercent': 'NIL'}, {'sourceProjectLabel': 'Porto Playa', 'unitsLaunched': 141, 'unitsSold': 139, 'netSalesAEDMillion': 361, 'revenueBacklogAEDMillion': 344, 'reportedSoldPercent': 98, 'reportedCompletePercent': 5}]};assert reviewed['sourceSHA256']==financial_source['sha256'] and reviewed['reviewedPage']==30
 for row in reviewed['rows']:
  label=row['sourceProjectLabel']
  if label not in by_label and label!='NB Collections':continue
  rid=NB if label=='NB Collections' else by_label[label]['recordId'];r=records[rid];assert r['type']=='project' and r['emirate']=='Ras Al Khaimah'
  key={'Bayviews':'bayviews','Marbella Extension':'marbella2','Cape Hayat':'cape','Quattro Del Mar':'quattro','The Edge':'edge','Porto Playa':'porto','NB Collections':'nb'}[label]
  priorproof='rak37-nb-launch' if rid==NB else next(p for p in oldchecks[rid]['sourceIds'] if not p.startswith('rak35-'))
  proof=[financial_source['id'],priorproof]
  basis=f"Exact existing {r['name']} record matches the primary identity release and the FY2024 developer table."
  if key=='marbella2':basis+=' Marbella Extension is the 89-home Phase 2, not the original 205-home project.'
  if key=='porto':basis+=' Native table figures retain the 50% JV equity-accounting basis; no whole-project doubling.'
  if key=='quattro':basis+=' The 888 launched units are a dated table population, retained alongside the Q2 figure of 631; no catalogue inventory overwrite.'
  if key=='nb':basis+=' The dated launch identifies 11 NB Collection villas on Hayat Island; the report plural NB Collections and 11-unit population refer to the same project.'
  report={**{k:v for k,v in row.items() if k!='reportedCompletePercent'},'asOf':'2024-12-31','reportingPeriod':'2024','sourcePage':30,'reportedConstructionComplete':row['reportedCompletePercent'],'currency':'AED','nativeMonetaryScale':1000000,'populationBasis':'50% share as per JV equity accounting; native reported values, not whole-project totals' if key=='porto' else 'Developer table project population; launched and sold cohorts, not a registered-transaction extract','periodBasis':'Cumulative project snapshot as of 31 December 2024; not sales occurring only during December or 2024','pricePerUnitDerived':False,'registeredTransactionsEstablished':False}
  facts.append({**common(rid,key+'-reported-sales',financial_source['id'],basis,proof),'kind':'financial','scope':'subject','evidenceClass':'primary_developer_reported_aggregate_sales','observation':{'metric':'volume','value':row['unitsSold'],'unit':'developer-reported units sold'+(' (50% JV reporting basis)' if key=='porto' else ''),'period':'2024-12-31','frequency':'daily','observationKind':'developer_reported_aggregate_sales','currentSnapshotEligible':False,'includeInCurrentSnapshot':False,'observationDateBasis':report['periodBasis'],'note':'Developer cumulative sales and revenue backlog are not registered transactions, cash collections, unit prices or valuations. Even a row with one reported unit does not establish a registered sale or an individual property price. No averages or period-to-period sales flows are derived.','developerSalesSnapshot':report}})
  p=row['reportedCompletePercent']
  life(rid,key+'-progress',financial_source['id'],basis,proof,'construction_progress_not_reported' if p=='NIL' else 'construction_progress',{'start':'2024-12-31','precision':'day'},f'Developer reports {p}% construction completion as of 31 December 2024.' if p!='NIL' else 'Developer table reports construction completion as NIL at 31 December 2024.','Reported progress is not an inspection, legal completion certificate, occupancy or rental commencement. NIL remains literal and does not establish numeric zero. Earlier reporting vintages remain unchanged.',sourcePage=30,dateBasis='FY2024 investor report table as of 31 December 2024',**({'progressPercent':p} if p!='NIL' else {}))
  checks.append({'recordId':rid,'catalogueName':r['name'],'type':r['type'],'emirate':r['emirate'],'identityVerified':True,'sourceIds':proof,'basis':basis});native.append({'recordId':rid,**report})
  if key=='nb':life(rid,'nb-announcement','rak37-nb-launch',basis,['rak37-nb-launch'],'announcement',{'start':'2024-06-26','precision':'day'},'RAK Properties announces the 11-villa NB Collection on Hayat Island.','Dated developer announcement, not proof of first-ever marketing, first sale, construction start or earlier land-value inapplicability.',verification='verified',dateBasis='Developer release date displayed as 26 June 2024')
 basis='Exact Mina Al Arab community record in Ras Al Khaimah. Named operating hotels are community components only, not branded residences or whole-community occupancy.'
 life(MINA,'mina-anantara-opening',financial_source['id'],basis,[financial_source['id']],'phase_opening',{'start':'2024-01-02','precision':'day'},'Developer reports Anantara Mina Al Arab hotel opened on 2 January 2024.','Hotel opening does not establish residential occupancy, apartment rents or a property-price uplift.',scope='subject_phase',sourcePage=10,phaseLabel='Anantara Mina Al Arab hotel',dateBasis='FY2024 investor timeline explicitly dates the hotel opening',relatedMilestoneIds=['rak36-mina-anantara-opening-target','rak36-mina-anantara-completion-target'],dateReconciliation='Actual opening report retained alongside earlier 2019 opening and 2021 completion targets; those targets are not overwritten.')
 life(MINA,'mina-intercontinental-opening-report','rak37-ihg-opening-2022',basis,['rak37-ihg-opening-2022'],'phase_opening_report',{'start':'2022-03-03','precision':'day'},'IHG reports that InterContinental Mina Al Arab has opened, in its 3 March 2022 release.','The date is the opening announcement publication day, not a verified first operating day. This hotel component supplies no residential occupancy, rents or price uplift.',scope='subject_phase',phaseLabel='InterContinental Ras Al Khaimah Mina Al Arab Resort & Spa',dateBasis='Dated operator announcement; opening had occurred by publication, exact first operating day unestablished',relatedMilestoneIds=['rak36-mina-intercontinental-opening-target','rak36-mina-intercontinental-completion-target'],dateReconciliation='Opening reported by March 2022 is retained alongside earlier 2019 opening and 2021 completion targets. No fabricated exact opening day.')
 r=records[MINA];checks.append({'recordId':MINA,'catalogueName':r['name'],'type':r['type'],'emirate':r['emirate'],'identityVerified':True,'basis':basis})
 for rid in {f['recordId'] for f in facts}:
  ids={f['id'] for f in facts if f['recordId']==rid}|{f['id'] for f in records[rid]['lifecycle']}
  assert all(set(f.get('relatedMilestoneIds',[]))<=ids for f in facts if f['recordId']==rid)
 collection={'projectRecords':7,'communityRecords':1,'acceptedLifecycleFacts':10,'acceptedDeveloperSalesSnapshots':7,'newSources':3,'registeredSaleOrRentObservationsAdded':0,'currentValuationsAdded':0,'unitPricesDerived':0,'approved2080Forecasts':0,'rawBodiesRedistributed':False}
 packet={'version':1,'passId':'rak-financial-pass37-20261008','asOf':s['asOf'],'priorVersion':s['version'],'candidateVersion':'20261008-enrichment-v37','sources':sources,'facts':facts,'seriesLinks':[],'recordIdentityChecks':checks,'nativeSalesSnapshots':native,'collection':collection,'conflicts':[{'field':'units_launched','resolution':'Quattro Q2 and FY2024 launched populations differ; both dated snapshots retained. No subtraction presented as comparable sales flows.'},{'field':'hotel_openings','resolution':'Hotel opening reports retain native date semantics and superseded targets; they do not establish residential occupancy.'}],'excludedCandidates':oldpacket['excludedCandidates']+[{'field':'corporate_investment_property_valuations_and_rents','reason':'2024 and 2025 audited statements report portfolio totals and valuation-input ranges without exact catalogue property identities. No allocation to projects or communities, per-unit division or current valuation credit.'},{'source':'minor-opening-2024','reason':'Direct operator capture failed; no source or coverage credit. Exact Anantara opening date is separately supported by reviewed developer report.'}],'methodology':'Visually reviewed native table and timeline, checksummed primary captures, exact identity proofs and separately preserved reporting vintages. No average prices, registered sale inference, aggregate portfolio valuation allocation, NIL-to-zero conversion, hotel-to-residence fan-out or inferred historical online availability.'}
 assert len(facts)==17 and len(checks)==8
 (BASE/'rak-properties-financial-pass37-20261008.json').write_text(json.dumps(packet,ensure_ascii=False,indent=2)+'\n');print(json.dumps(collection))
if __name__=='__main__':main()
